import json
import os
import boto3
import base64
import logging
from datetime import datetime, timedelta
from collections import defaultdict
import random

# Configure logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Environment variables
TABLE_NAME = os.getenv('TABLE_NAME', 'narrative-state')
BUCKET_NAME = os.getenv('BUCKET_NAME', 'narrative-store')
STREAM_NAME = os.getenv('STREAM_NAME', 'user-events')
USE_MOCK_AI = os.getenv('USE_MOCK_AI', 'true').lower() == 'true'
STORY_TONE = os.getenv('STORY_TONE', 'reflective')
ENDPOINT_URL = os.getenv('AWS_ENDPOINT_URL')

def get_client(service):
    """Get AWS client with proper endpoint"""
    if ENDPOINT_URL:
        return boto3.client(service, endpoint_url=ENDPOINT_URL, region_name='us-east-1')
    return boto3.client(service, region_name='us-east-1')

def get_resource(service):
    """Get AWS resource with proper endpoint"""
    if ENDPOINT_URL:
        return boto3.resource(service, endpoint_url=ENDPOINT_URL, region_name='us-east-1')
    return boto3.resource(service, region_name='us-east-1')

dynamodb = get_resource('dynamodb')
s3 = get_client('s3')
table = dynamodb.Table(TABLE_NAME)

def process_kinesis_records(records):
    """Process events from Kinesis"""
    processed = 0
    errors = 0
    
    for record in records:
        try:
            # Decode event data
            encoded_data = record['kinesis']['data']
            decoded_data = base64.b64decode(encoded_data).decode('utf-8')
            event = json.loads(decoded_data)
            
            logger.info(f"Processing event: {event.get('event_id', 'unknown')}")
            
            # Store in DynamoDB
            event_id = event.get('event_id')
            event_type = event.get('type')
            user_id = event.get('user_id', 'unknown')
            timestamp = event.get('timestamp', datetime.now().isoformat())
            data = event.get('data', {})
            date = timestamp[:10]
            
            table.put_item(
                Item={
                    'pk': f"user::{user_id}",
                    'sk': f"event::{timestamp}",
                    'gsi1pk': f"day::{date}",
                    'gsi1sk': timestamp,
                    'event_type': event_type,
                    'event_id': event_id,
                    'event_data': json.dumps(data)
                }
            )
            
            # Store in S3
            s3_key = f"raw/user={user_id}/year={date[:4]}/month={date[5:7]}/day={date[8:10]}/{event_id}.json"
            s3.put_object(
                Bucket=BUCKET_NAME,
                Key=s3_key,
                Body=json.dumps(event, indent=2)
            )
            
            processed += 1
            
        except Exception as e:
            logger.error(f"Error processing record: {e}")
            errors += 1
    
    return {'processed': processed, 'errors': errors}

def generate_story(user_id, date=None):
    """Generate a story from events"""
    if not date:
        date = datetime.now().strftime("%Y-%m-%d")
    
    # Query events from DynamoDB
    response = table.query(
        IndexName='GSI1',
        KeyConditionExpression="gsi1pk = :pk",
        ExpressionAttributeValues={":pk": f"day::{date}"}
    )
    
    events = []
    for item in response.get('Items', []):
        if item['pk'] == f"user::{user_id}":
            events.append({
                'timestamp': item['sk'].replace('event::', ''),
                'type': item['event_type'],
                'data': json.loads(item.get('event_data', '{}'))
            })
    
    if not events:
        return f"No events found for {date}"
    
    events.sort(key=lambda x: x['timestamp'])
    
    # Generate simple story
    story = f"# Daily Narrative - {date}\\n\\n"
    story += f"Today you had {len(events)} digital moments.\\n\\n"
    
    # Group events by type
    event_counts = defaultdict(int)
    for event in events:
        event_counts[event['type']] += 1
    
    for event_type, count in event_counts.items():
        story += f"- {count} {event_type} event(s)\\n"
    
    story += "\\n*Generated by Narrative Engine*"
    
    # Save story
    local_path = f"/tmp/story_{date}.md"
    with open(local_path, 'w') as f:
        f.write(story)
    
    return story

def lambda_handler(event, context):
    """Main Lambda handler"""
    logger.info(f"Lambda invoked")
    
    # Check if this is a Kinesis trigger
    if 'Records' in event and event['Records']:
        first_record = event['Records'][0]
        if 'kinesis' in first_record:
            result = process_kinesis_records(event['Records'])
            return {
                'statusCode': 200,
                'body': json.dumps(result)
            }
    
    # Handle direct invocation
    action = event.get('action', 'generate_daily_narrative')
    user_id = event.get('user_id', 'default-user')
    
    if action == 'generate_daily_narrative':
        date = event.get('date', datetime.now().strftime("%Y-%m-%d"))
        story = generate_story(user_id, date)
        
        return {
            'statusCode': 200,
            'body': json.dumps({
                'message': 'Story generated',
                'story': story,
                'date': date
            })
        }
    
    return {'statusCode': 400, 'body': json.dumps({'error': 'Unknown action'})}